export const GET_ERRORS = "GET_ERRORS";
export const GET_DEPLOY_RECORDS = "GET_DEPLOY_RECORDS";
export const GET_DEPLOY_RECORD = "GET_DEPLOY_RECORD";
export const DELETE_DEPLOY_RECORD = "DELETE_DEPLOY_RECORD";

export const SET_CURRENT_USER = "SET_CURRENT_USER";
